### ISSUE TITLE
Create and publish a docker image containing the evaluator script

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/frx-challenges#107]
We need an autopublishing docker image that contains the evaluator script and can be easily and consistently used by both us and end users.

## Definition of done

- [ ] A docker image is automatically published to quay.io with the evaluator script
- [ ] GitHub actions will build and publish this image on each PR
- [ ] This image can be private until Oct 23, at which point it will be made public

**Comment by jnywong** [comment]
I think this is related to https://github.com/2i2c-org/unnamed-thingity-thing/issues/52#issuecomment-2436648020

**Comment by jnywong** [comment]
Closed by https://github.com/janelia-cellmap/cellmap-segmentation-challenge/pull/35
