### ISSUE TITLE
[Spike] Make a plan for managing secret ground truth

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/frx-challenges#109]
The ground truth against which we compare the submissions must be kept secret, yet available to our online evaluator. We must have a simple yet reasonable system in place for handling this.

## Questions to answer

- [x] How big will the ground truth file get? (order of magnitude is enough)
- [x] How often will it change?
- [x] Who is responsible for creating the file, and deciding it needs to change?
- [x] Will we have to re-score the old submissions when this file changes?

## Definition of done

- [x] We have answers to all these questions
- [x] There's a plan for where this secret file should be stored
- [ ] There's a plan for who has access and who manages access
- [ ] There's a plan for how this gets deployed to the evaluator

**Comment by rhoadesScholar** [comment]
### Questions answered:

1. Ground truth (GT) should be in the single digits of GB range (maybe low double digits at most).
2. **_Once set_**, the ground truth should not change for the duration of the challenge.
3. We (Yurri, Aubrey, and I) will be responsible for constructing the GT file and ensuring that it is properly formatted.
4. Again, as far as I am concerned, the GT test data should not change for the duration of the challenge. _**If**_ it did for unforeseen circumstances, old submissions would indeed need to be rescored. The inconvenience this entails in terms of long term data management is one of the reasons why I don't want us to ever have to change the GT file. ;)

**Comment by rhoadesScholar** [comment]
@yuvipanda After discussing with the team, the answer for 4 has changed: We may want to rescore if we change the metrics we want - so, yes, we need to hold on to submission data longterm.

**Comment by yuvipanda** [comment]
Ok, so I've decided we're going to:

1. Store the ground truth in a GCS bucket (separate buckets for fake one and real one)
2. Access to that is controlled by 2i2c (and can be granted to people who need to upload the bucket)
3. It's fetched and stored in the PVC via an initContainer (with `gcloud storage rsync`)

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/frx-challenges/issues/109#issuecomment-2420352260 has been implemented
