### ISSUE TITLE
[Spike] Understand how the output of the evaluator script maps onto the leaderboard

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/frx-challenges#116]
As we work with the 'real' evaluation script, we need to adjust our leaderboard to work

We need to understand and have explicit documentation on:

1. What the fields in the output JSON mean
2. What they should be called in the leaderboard
3. Are they likely to change in the future (more additions?)
4. What way should these be sorted?

## Definition of done

- [ ] These questions are answered
- [ ] Any new follow-up work from these answers are identified

**Comment by rhoadesScholar** [comment]
1. The results json is a dictionary with the following structure:
```json
    {
        "volume" (the name of the ground truth volume): {
            "label" (the name of the predicted class): {
                (For semantic segmentation)
                    "iou": (the intersection over union score),
                    "dice_score": (the dice score),

                OR

                (For instance segmentation)
                    "accuracy": (the accuracy score),
                    "haussdorf_distance": (the haussdorf distance),
                    "combined_score": (the geometric mean of the accuracy and haussdorf distance),
            }
        }
    }
```
2. How to summarize results in the leaderboard needs a lot more discussion with @avweigel, @funkey, etc.. For instance:
    a. Do we combine scores across test volumes?
        - Simplest approach: Yes - we combine scores across volumes based on the number of voxels in each volume. I can add this to the dictionary.
        - Caveat: It might be useful to know what samples are difficult for each model, both for the participants and for anyone hoping to use the resulting models for their own purposes.
    b. Do we combine scores across labels?
        - I don't think we should, except maybe for one _overall_ score. We want participants to be able to shine for just doing one organelle really well.
    c. Do we count missing volumes as the worst score?
        - I think yes, this seems the fairest approach.
    d. Is the main score for semantic segmentation IOU or Dice?
        - I am totally agnostic here.
3. I suspect new metrics may well be added in the future, yes.
4. More discussion needed. See #2.

Regarding #'s 2 and 4, I think this comes down to how complicated of a leaderboard we want to allow. Allowing users to sort submissions by scores on different organelles would be pretty cool, but also requires a dynamic interface.

**Comment by yuvipanda** [comment]
@rhoadesScholar for the oct 23 launch, I propose the following:

1. Whatever values should be in the leaderboard, should be output by the evaluator script. I don't want to do any custom computation (summation across values, etc) in the web app. Does this seem fine?
2. We can have multiple columns in the leaderboard, but let's target only a single leaderboard for the oct 23 launch

Does that seem right? We can add more work later, but I want to make sure that our delivery happens on time and is reliable when it does.

Re: 4, Did you mean to link to that issue or was that a reference to something else?

**Comment by yuvipanda** [comment]
@rhoadesScholar great. Can you add any one metric to the top level now, so I can make sure that gets represented properly in the leaderboard? Would help with development.

**Comment by rhoadesScholar** [comment]
https://github.com/janelia-cellmap/cellmap-segmentation-challenge/pull/36
