### ISSUE TITLE
Leaderboard goes back to first page of entries

### ISSUE THREAD

**Issue by funkey** [2i2c-org/frx-challenges#120]
### Context

The leaderboard seems to refresh itself every couple of seconds. That also resets the page to the first 10 entries, which makes it hard to look at other entries on later pages.

**Comment by jnywong** [comment]
Hello @funkey,

Thanks for opening this issue. The way that the leaderboard is updated will now be superseded by work in #177 that you can follow, where this bug will not be an issue anymore.

Forgive us that the codebase is undergoing rapid development, but please do open another issue if you see something super wrong!
