### ISSUE TITLE
Add notification flow when new users are added to a team

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/frx-challenges#147]

**Comment by yuvipanda** [comment]
This may be a bunch of work, so we should be careful to commit to it. We particularly do not want to commit to anything involving sending email at least for a while.

**Comment by jnywong** [comment]
Absolutely!

Eventually I think `django-notifications` is the right extension to bootstrap us here but they [don't support Django 5.x yet.](https://github.com/django-notifications/django-notifications/pull/375).

**Comment by jnywong** [comment]
The concept of a team is now removed. Submission owners can add users on a per-submission basis so that users can then see it in their own submissions portal. Closing as not planned.
