### ISSUE TITLE
[P&S Initiative] Launch CellMap Segmentation Challenge

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/frx-challenges#162]
This issue tracks the overall 2i2c Platform & Services team's initiative to fully launch the cellmap segmentation challenge.

Note: This issue was started halfway after the start of the project, so is not necessarily fully complete.

The production website is at https://cellmapchallenge.janelia.org/.

## Team

**Accountable for Project Completion**: @yuvipanda (but being transitioned to @jnywong)
**Tech Lead**: @yuvipanda 
**Infrastructure Engineers**:  @GeorgianaElena, @yuvipanda 
**Application Engineers**: @jnywong, @GeorgianaElena, @yuvipanda 

## Epics

- ✅ Launch static site (Oct 29) (No EPIC was setup for this, but issues were tracked in the Engineering Board)

**Comment by Gman0909** [comment]
It is apparent that we have blown past our time-boxed allocation of ~50 hours of dev time for this project, which was one of the key conditions for accepting the project in the first place. We should focus on the minimum viable deliverable over the next couple of weeks to get this launched and off our plate of active priorities. @jnywong will be leading the effort to deliver this.

**Comment by Gman0909** [comment]
@yuvipanda Just noting that this has an end date of Nov 22nd

**Comment by yuvipanda** [comment]
I've done the following:

1. Set this one's end date to end of the current sprint, at which point it'll transition into ongoing maintenance (we're contracted to do that for a year).
2. We don't have full control over the actual launch date, and I don't currently know when that is.
3. Added the things that need to be done to get to technical feature complete as sub issues.

At this point, it's just me working on it.

**Comment by yuvipanda** [comment]
https://2i2c.slack.com/archives/C06RX73KF2R/p1729196722224909 is the thread to follow with cellmap about launch date

**Comment by yuvipanda** [comment]
This is feature complete! We'll have to co-ordinate with cellmap for actually launching the challenge and maintaining it for the next year, but primary features are all complete and rolled out now.

Excellent kudos to @GeorgianaElena and @jnywong for getting this here!

**Comment by Gman0909** [comment]
Fantasic work
