### ISSUE TITLE
Resolve deployment to staging following project rename

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/frx-challenges#171]
Related to #98 

As you might expect, renaming the entire project is pretty disruptive.

I've managed to migrate the entire chartpress workflow, but I don't have the skills to know whether renaming `unnamed` to `frx-challenges` in the various helm charts worked (see https://github.com/2i2c-org/frx-challenges/pull/148).

When doing a local deployment to staging using https://github.com/2i2c-org/segmentation-challenge-deploy/pull/42 as the source, I run into the following error

```
> python3 deployer.py app --namespace=staging                                                                                    
Fetching cluster endpoint and auth data.                                                                                                                                                                                      
kubeconfig entry generated for openorganelle.                                                                                                                                                                                 
Running helm upgrade --install --create-namespace --wait --namespace=staging staging /Users/jnywong/Documents/github/segmentation-challenge-deploy/helm-charts/app --values=/Users/jnywong/Documents/github/segmentation-chall
enge-deploy/helm-charts/app/common.values.yaml --values=/Users/jnywong/Documents/github/segmentation-challenge-deploy/helm-charts/app/staging/staging.values.yaml --values=/var/folders/cf/9rjbnz9s2t73k23s1r0j2ds40000gn/T/tmp689mtcs7                                              
Error: UPGRADE FAILED: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "staging.cellmapchallenge.2i2c.cloud" and path "/" is already defined in ingress staging/staging-unnamed
```

**Comment by yuvipanda** [comment]
Because renaming a helm chart is a fairly intrusive operation (all the resource names have the chart name in thtem by default, for example (something I hate, but I digress)), the easiest way to do this is to undeploy the old release and deploy anew. But because we have data on disk, this is actually destructive to that data.

So we have to:

1. Copy the data locally
2. Undeploy the old helm release
3. Deploy new one

Let me try to do this and livestream it for posterity.

**Comment by yuvipanda** [comment]
Done!
