### ISSUE TITLE
Complete UI for managing Submissions

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/frx-challenges#176]
This epic tracks completing all the UI / UX functionality required for handling submissions. 

## Definition of Done

- [x] Users can *create* new submissions
- [x] Users can *fill in metadata* about new submissions
- [x] Users can *upload a new version* of a submission
- [x] Users can see the *progress of their submission version being evaluated*
<s>- [ ] Users can hide any particular version of their submission from public view if they need.</s>

## UI Views that must be completed

As a logged in user, I must be able to:

- [x] See a list of all my submissions
- [x] Create a new submission
- [ ] Edit the metadata about any of my submissions

As a *logged out* user, I should be able to:

- [x] See a list of *all* submissions
- [x] See metadata about each submission
<s>- [ ] See list of non-hidden versions for each submission</s>

We will not be doing anything for deleting submissions at that time. If necessary, it can be handled via the django admin.

## Metadata to be collected for each submission

This should all be *configuration* rather than be hardcoded in the code.

| Name | Description | Type |
| - | - | - |
| Submission Name | Name of the Submission itself | Textbox |
| Submission Source Code | URL to Source of Submission (if Open Source ) | TextBox (with URL requirement) |

However, the following should be handled as part of the code:

- [x] terms and conditions should be a checkbox that must be checked before submit is available. The content of this checkbox's label should be markdown that is set by a config variable.

## Key differences from UX prototype

Key differences from https://preview.uxpin.com/0abb8096b7601d53666f623a9db9b53431b7853b#/pages/186520148/simulate/sitemap

1. No conditional fields (there, the submission source code field is only available if a checkbox is ticked)
2. Submission and user profile are handled separately here (they are handled together over there)

**Comment by yuvipanda** [comment]
Going to trim this feature as well:

> Users can hide any particular version of their submission from public view if they need.

as instead we only show the 'best' performing version from the leaderboard anyway.

**Comment by yuvipanda** [comment]
*Most* of these have been handled with the open PRs I think. Left to do is an edit view for submissions, and decide how to handle detail views for particular versions.

**Comment by jnywong** [comment]
I've gone through and checked off all the features that were handled by the PRs I have just reviewed and merged. The only remaining one is editing submission metadata after being created.
