### ISSUE TITLE
Complete UI for Leaderboards

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/frx-challenges#177]
This issue tracks the UI we have for showing leaderboards.

## Definition of done

- [x] Leaderboards are shown *per submission* rather than *per version* (as they are now)
- [x] Clicking a link in the leaderboard takes you to the submission page for that submission
- [x] The *latest* scores are displayed for each submission
<s>- [ ] Pagination of the leaderboard works as you would expect</s>

**Comment by yuvipanda** [comment]
Going to remove "pagination" as a feature, and just put everything on one page but sorted correctly.

**Comment by jnywong** [comment]
DoD completed, marking as closed.
