### ISSUE TITLE
Replace "Groups" with submission-level access controls

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/frx-challenges#180]
We had the notion of "groups" (or teams) to have multiple users who can submit to a common set of submissions. This added a bunch of complexity. Instead, let's rip it out and add per-submission collaboration.

So for each submission, the submission admin (initially the original creator) can grant others permissions to upload new versions to a submission. This allows for multiple people to collaborate on any given submission without having to have a more complex datamodel.

## Definition of done

- [x] All notions of team are removed from codebase
- [x] CRUD for users to be able to grant others access to a submission they have created

**Comment by yuvipanda** [comment]
Should include https://github.com/2i2c-org/frx-challenges/issues/188

**Comment by jnywong** [comment]
Closed by #195  and #196 🎉

**Comment by jnywong** [comment]
There's now a new "Collaborator" model that submission owners can use to CRUD collaborators through the submission detail page.

Admins can also edit in the admin view of the website.

**Comment by yuvipanda** [comment]
Yay great!

Can we add some validation and help text to let people know we can only add users who have already logged in at least once? Right now if I add a user who has not logged in yet, I get 

![Image](https://github.com/user-attachments/assets/763f7ef7-c015-4ec5-8a42-1fc5946b033d)
