### ISSUE TITLE
Complete UI for showing versions of a submission

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/frx-challenges#189]
After uploading a version of a submission, we currently put the user back to the overall submission page, where they can see the progress of the submission in a table. This is somewhat confusing and hard to spot.

Instead, we should have a 'view' page for each submission version that shows the current state of the submission.

## Definition of done

- [x] There's a 'view' page for each submission version
- [x] Upon uploading a new version of a submission, user is redirected to this view page

No editing functionality is provided at this time.

**Comment by rhoadesScholar** [comment]
- [ ] Error messages / results are shown on the submission page.

**Comment by yuvipanda** [comment]
Error logs are now stored in the database, and available for admins to view. So far I've intentionally chosen to *not* make error logs visible to prevent accidentally leaking ground truth. Also not showing the entire result JSON out - but we can change config to expose any of the specific fields as needed!
