### ISSUE TITLE
Update text of the Cellmap Challenge site to announce the launch

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/frx-challenges#220]
New text with details is expected by Thursday Dec 12, and set up to launch by Dec 16

## Definition of Done

- [x] New text updated in the website

**Comment by avweigel** [comment]
Text is below. Can we make the citations superscript (1-5)? Please add any other formatting that you think will make the text better.

# About

## The Challenge

The CellMap Segmentation Challenge presents a richly detailed collection featuring 289 meticulously annotated training volumes, each vetted by multiple experienced annotators for use in machine learning network development. All of the data is part of the collection DOI: [10.25378/janelia.c.7456966](https://doi.org/10.25378/janelia.c.7456966) and be explored on [OpenOrganelle](https://openorganelle.org).  This diverse dataset encompasses 22 eFIB-SEM datasets and over 40 unique classes of organelles, providing a wide array of cellular structures for analysis.  In the sections below are a summary of the datasets. If you want to learn more about all of the data included, please refer to the collection DOI write-up.

The challenge offers participants the opportunity to advance AI-driven image segmentation by leveraging detailed and accurate annotations across a broad spectrum of organelle classes. This allows participants to develop and refine their models with high-quality data while creating algorithms that are adaptable and effective in various biological contexts and imaging conditions. With such a vast and well-annotated dataset, the challenge sets the stage for significant breakthroughs in electron microscopy image analysis, potentially transforming our understanding of cellular architecture and function.

## How to Access the Data

Participants can access the CellMap Segmentation Challenge data by following these steps:

1. **Visit the GitHub Repository:** Go to the official [GitHub repository](https://github.com/janelia-cellmap/cellmap-segmentation-challenge). This repository contains detailed instructions, scripts, and resources needed to download the data, train models, make predictions, and submit results.
2. **Download the Data:** Use the provided download scripts and follow the guidelines outlined in the repository documentation to retrieve the datasets.
3. **Train Your Model:** Refer to example code and tutorials available in the repository to train machine learning models on the provided data.
4. **Make and Submit Predictions:** Follow the prediction submission guidelines in the repository to submit results for evaluation. Submissions will open in early 2025.
5. **Participate and Stay Updated:** Keep an eye on updates and announcements through the GitHub repository and related community channels. Subscribe for email updates [here](https://janelia.us5.list-manage.com/subscribe?u=3c8034ebf5d74492b5c8ef8c9\&id=ec5465eb32).

## The Data

The training volumes used in the CellMap Segmentation Challenge are derived from 22 distinct eFIB-SEM datasets, including 9 cell culture samples and 13 tissue samples. These samples come from a variety of organisms, including mouse, *Drosophila*, zebrafish, and human. The tissue types span key biological regions and organs such as the brain, heart, liver, and kidney, offering a broad spectrum of biological contexts for participants to explore.

The datasets were acquired using enhanced Focused Ion Beam Scanning Electron Microscopy (eFIB-SEM)[1](https://elifesciences.org/articles/25916),[2](https://patents.google.com/patent/US10600615B2/en),[3](https://link.springer.com/protocol/10.1007/978-1-0716-0691-9_12), at ultra-high resolutions of 4 nm or 8 nm isotropic voxel sizes. The datasets were prepared using different preservation techniques, including both chemical fixation and high-pressure freezing. These varying preparation methods introduce additional complexity, requiring participants to develop segmentation algorithms capable of handling subtle differences in sample preparation and imaging quality.

Participants can access the data through the official [GitHub repository](https://github.com/janelia-cellmap/cellmap-segmentation-challenge), which includes scripts and instructions for downloading the datasets, training models, making predictions, and submitting results. The dataset is publicly available through the collection DOI: [10.25378/janelia.c.7456966](https://doi.org/10.25378/janelia.c.7456966), which should be cited in any related work.

## The Annotations

The datasets in the CellMap Segmentation Challenge include nearly 80 distinct organelle and substructure classes, representing a wide variety of cellular components. The annotations are an extension of work started by the COSEM Project Team[4](https://www.nature.com/articles/s41586-021-03977-3). Each of the 289 training volumes has been carefully annotated by a team of experts, ensuring high accuracy and consistency[5](https://dx.doi.org/10.17504/protocols.io.bp2l61rb5vqe/v3). These dense annotations span a range of cellular structures, from larger, easily recognizable organelles to intricate subcellular details, providing participants with a robust and diverse dataset for segmentation.

Among these 80 classes, 47 are well-represented, each appearing in at least three volumes from three different datasets. These 47 classes form the core set for evaluation and leaderboard placement. The comprehensive range of annotated organelles and substructures encourages participants to develop advanced segmentation algorithms capable of handling both common and less frequently observed cellular features.

A more detailed technical write-up will be available in early 2025 providing an in-depth analysis of annotator variability. This analysis highlights the inherent challenges in annotating complex cellular structures, offering valuable insights into the nuances of the dataset and aiding in its interpretation.

## CellMap Project Team Members

David Ackerman, Emma Avetissian, Davis Bennett, Marley Bryant, Grace Park, Alyson Petruncio, Alannah Post, Jacquelyn Price, Diana Ramirez, Jeff Rhoades, Rebecca Vorimo, Aubrey Weigel, Marwan Zouinkhi, and Yurii Zubov

## CellMap Steering Committee Members

Misha Ahrens, Christopher Beck, Teng-Leong Chew, Daniel Feliciano, Jan Funke, Harald Hess, Wyatt Korff, Jennifer Lippincott-Schwartz, Zhe J. Liu, Kayvon Pedram, Stephan Preibisch, Stephan Saalfeld, Ronald Vale, and Aubrey Weigel

**Comment by avweigel** [comment]
About blurb on the [main page](https://cellmapchallenge.janelia.org) updated text:

Welcome to the CellMap Segmentation Challenge! This competition provides 289 meticulously annotated training volumes from 22 diverse eFIB-SEM datasets, covering over 40 unique organelle classes. Participants will leverage these high-quality annotations to develop AI-driven segmentation models, advancing our understanding of cellular structures across various biological contexts. With this richly detailed dataset, the challenge sets the stage for significant breakthroughs in electron microscopy image analysis and cellular architecture exploration. The data is publicly available on [OpenOrganelle](https://openorganelle.org) with a [collection DOI](https://doi.org/10.25378/janelia.c.7456966). For detailed instructions on accessing the data, participating in the challenge, and submitting predictions, visit the official [GitHub repository](https://github.com/janelia-cellmap/cellmap-segmentation-challenge).

**Comment by jnywong** [comment]
Hey @avweigel ! I have just updated the text for you: https://cellmapchallenge.janelia.org/

Please have a quick check through that everything is okay 👍

**Comment by avweigel** [comment]
Dates on the main page:

SEP 29 2024 Email registration opens
DEC 16 2024 Challenge begins - Data is live!
JAN 2025 Submissions open
JAN 2026 Winners announced

**Comment by jnywong** [comment]
Okay, I've reverted but updated the dates on the main homepage: https://cellmapchallenge.janelia.org/

The staging website retains all of the proposed changes that you can still preview: https://staging.cellmapchallenge.2i2c.cloud/

**Comment by jnywong** [comment]
Text on the live site updated. 

Once the challenge status is running, @avweigel should be able to open an account and have Django admin access to have permissions to maintain the Pages over the duration of the challenge.
