### ISSUE TITLE
Rename this open source project

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/frx-challenges#98]
In https://github.com/2i2c-org/unnamed-thingity-thing/issues/15, we had settled on `frx-challenges` as the name of this open source project. Now we have to execute the change.

## Things to rename

- [x] Repository
- [x] Django Project https://github.com/2i2c-org/frx-challenges/pull/174
- [ ] Django App
- [x] Helm Chart Publication Location
- [x] Helm Chart Name
- [x] Docker image
- [ ] ???

**Comment by jnywong** [comment]
> - [ ] Django App

Now that the parent `comptest` folder is renamed  to `frx_challenges` with sub-folders `frx_challenges` and `web` for the apps, I am going to leave the web app named `web` for clarity.

Marking this as closed.
